- name: Download Multilingual Lexicons
  logo: /img/multilingual.png
  featured: true
  url: Multilingual
- name: Lexicon Development Services
  logo: /img/categories/planning-zoning.svg
  featured: true
  url: LexiconDevelopment
- name: Lexicon Visualisation Services
  logo: /img/dataviz.jpeg
  featured: true
  url: LexiconVisualisation
- name: LiveLanguage Learning
  logo: /img/categories/education.svg
  featured: true
  url: Learning
- name: NLP Services
  logo: /img/categories/languages.jpg
  featured: true
  url: NLP
