- name: Download Multilingual Lexicons
  logo: /img/multilingual.png
  featured: true
  url: http://dsauthproxy.knowdive.disi.unitn.it/?res=LiveLanguage/Multilingual&enc=1
- name: Lexicon Development Services
  logo: /img/categories/planning-zoning.svg
  featured: true
  url: LexiconDevelopment
- name: Lexicon Visualisation Services
  logo: /img/dataviz.png
  featured: true
  url: LexiconVisualisation
- name: LiveLanguage Learning
  logo: /img/categories/education.svg
  featured: true
  url: Learning
- name: NLP Services
  logo: /img/nlp.png
  featured: true
  url: NLP
