- name: Languages of the world
  logo: /img/categories/world-map.png
  featured: true
  url: http://ukc.datascientia.eu/
- name: Languages of India
  logo: /img/india.png
  featured: true
  url: http://indo.ukc.datascientia.eu
- name: Arabic Languages
  logo: /img/arabic.png
  featured: true
  url: http://arabic.ukc.datascientia.eu
- name: Indonesian Languages
  logo: /img/indonesia.png
  featured: true
  url: http://indonesia.ukc.datascientia.eu
