# To add fields, make a new schema file in this directory
# and change the schema setting in _config.yml to its name
dataset_fields:
  - field_name: title
    label: Title
    datajson: title
  - field_name: organization #publisher
    label: Organization
    form_template: form/organization.html
    datajson: publisher.name
  - field_name: notes
    label: Description
    form_template: form/textarea.html
    datajson: description
  - field_name: category
    label: Category
    form_template: form/category.html
    display_template: display/category.html
    datajson: category
  - field_name: maintainer
    label: Maintainer
    datajson: contactPoint.fn
  - field_name: maintainer_email
    label: Maintainer Email
    datajson: contactPoint.hasEmail
  - field_name: tags
    label: Tags
    datajson: tags
  - field_name: provenance
    label: Provenance
    datajson: provenance
  - field_name: version
    label: Version
    datajson: version
  - field_name: dataset_level
    label: Dataset Level
    datajson: dataset_level
  - field_name: dataset_access
    label: Download Access Level
    datajson: dataset_access
  - field_name: dataset_description
    label: Dataset description document or page
    datajson: dataset_description
  - field_name: landing_page
    label: Landing Page
    datajson: landing_page
  - field_name: date_of_collection
    label: Date of Collection
    datajson: date_of_collection
  - field_name: linguistic_information
    label: Linguistic Information
    datajson: linguistic_information
  - field_name: latitude_map
    label: latitude
    datajson: latitude_map
  - field_name: longitude_map
    label: longitude
    datajson: longitude_map

resource_fields:
  - field_name: name
    label: Resource Name
    datajson: distribution.title
  - field_name: url
    label: URL
    datajson: distribution.url
  - field_name: format
    label: Format
    datajson: distribution.format
    form_template: form/dropdown.html
    values:
      - api
      - csv
      - tsv
      - rdf
      - json
      - geojson
      - html
      - kml
      - kmz
      - shp
      - xml
  - field_name: license
    label: License
    form_template: form/license.html
    datajson: license
  - field_name: last_updated
    label: Last updated
    datajson: last_updated
  - field_name: created
    label: Created
    datajson: created
  - field_name: size
    label: Size (Bytes)
    datajson: size
  - field_name: release_date
    label: Release Date
    datajson: release_date
  - field_name: distribution_document
    label: Distribution document or page
    datajson: distribution_document
  - field_name: language
    label: Language
    datajson: language
  - field_name: language_code
    label: ISO-3 language code
    datajson: language_code

organization_fields:
  - field_name: title
    label: Title
  - field_name: description
    label: Description
  - field_name: logo
    label: Logo

category_fields:
  - field_name: name
    label: Name
  - field_name: logo
    label: Logo
  - field_name: logo_credit
    label: Logo Credit
  - field_name: featured
    label: Featured on Homepage
    form_template: form/checkbox.html
